import "./globals.css";
import React from "react";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          // Hydration-safe inline script to set initial theme before paint
          dangerouslySetInnerHTML={{
            __html: `(() => {try {const k='color-scheme';const s=localStorage.getItem(k);let d=false;if(s==='dark'){d=true;} else if(s==='light'){d=false;} else {d=window.matchMedia('(prefers-color-scheme: dark)').matches;}document.documentElement.setAttribute('data-theme', d?'dark':'light');} catch(e) {}})();`,
          }}
        />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
